import { Nodeweave, type ConnectionPathContext, type NodeweaveOptions } from 'nodeweave';
import 'nodeweave/styles.css';
import './style.css';

const node = (id: string) => (context: ConnectionPathContext) => context.connection.id === id;
const curve = (id: string, render: (context: ConnectionPathContext) => string) => (context: ConnectionPathContext): string => node(id)(context) ? render(context) : '';

/** Consumer-owned Dexstoore desktop scene. Nodeweave itself has no knowledge of it. */
const dexstoore: NodeweaveOptions = {
  width: 960,
  height: 720,
  ariaLabel: 'Dexstoore connected systems',
  nodeDefaults: { geometry: { innerRingScale: .52, outerRingScale: .94 } },
  nodes: [
    { id: 'storefront', label: 'Storefront', detail: 'Browse · Checkout · Purchase', position: { x: 392, y: 88 }, labelPosition: { x: 434, y: 84 }, color: 'var(--orange)', geometry: { coreRadius: 4.16, spread: 28.6, particleCount: 55, innerRingScale: .5928, outerRingScale: 1.0716, microMarks: 5 } },
    { id: 'commerce-api', label: 'Commerce API', detail: 'Products · Orders · Customers', position: { x: 404, y: 206 }, labelPosition: { x: 446, y: 202 }, color: 'var(--cyan)', geometry: { coreRadius: 4.68, spread: 35.1, particleCount: 76, innerRingScale: .57, outerRingScale: 1.0944, microMarks: 6 } },
    { id: 'order-engine', label: 'Order Engine', detail: 'Processing · Assignment · Fulfillment', position: { x: 388, y: 334 }, labelPosition: { x: 430, y: 330 }, color: 'var(--violet)', geometry: { coreRadius: 5.46, spread: 46.8, particleCount: 114, innerRingScale: .5472, outerRingScale: 1.1628, microMarks: 8, hub: true } },
    { id: 'operations', label: 'Operations', detail: 'Manage · Support · Scale', position: { x: 108, y: 498 }, labelPosition: { x: 150, y: 494 }, color: 'var(--green)', geometry: { coreRadius: 3.64, spread: 24.7, particleCount: 47, innerRingScale: .6156, outerRingScale: 1.026, microMarks: 4 } },
    { id: 'fulfillment', label: 'Fulfillment', detail: 'Automated Delivery', position: { x: 648, y: 486 }, labelPosition: { x: 690, y: 482 }, color: 'var(--blue)', geometry: { coreRadius: 4.42, spread: 32.5, particleCount: 70, innerRingScale: .5814, outerRingScale: 1.083, microMarks: 6 } },
    { id: 'email', label: 'Email', detail: 'Delivery · Receipts', position: { x: 528, y: 628 }, labelPosition: { x: 570, y: 624 }, color: 'var(--red)', geometry: { coreRadius: 3.12, spread: 18.2, particleCount: 32, innerRingScale: .6384, outerRingScale: 1.0032, microMarks: 3 } },
    { id: 'whatsapp', label: 'WhatsApp', detail: 'Twilio Integration', position: { x: 752, y: 618 }, labelPosition: { x: 794, y: 614 }, color: 'var(--yellow)', geometry: { coreRadius: 3.12, spread: 18.2, particleCount: 32, innerRingScale: .6384, outerRingScale: 1.0032, microMarks: 3 } },
  ],
  connections: [
    { id: 'storefront-commerce-api', from: 'storefront', to: 'commerce-api', fromColor: 'var(--orange)', toColor: 'var(--cyan)', markers: {} },
    { id: 'commerce-api-order-engine', from: 'commerce-api', to: 'order-engine', fromColor: 'var(--cyan)', toColor: 'var(--violet)', markers: {} },
    { id: 'order-engine-operations', from: 'order-engine', to: 'operations', fromColor: 'var(--violet)', toColor: 'var(--green)', markers: {}, path: curve('order-engine-operations', ({ anchors: a }) => `M${a.start.x} ${a.start.y} C${a.start.x - 140} ${a.start.y + 70} ${a.end.x + 50} ${a.end.y - 110} ${a.end.x} ${a.end.y}`) },
    { id: 'order-engine-fulfillment', from: 'order-engine', to: 'fulfillment', fromColor: 'var(--violet)', toColor: 'var(--blue)', markers: {}, path: curve('order-engine-fulfillment', ({ anchors: a }) => `M${a.start.x} ${a.start.y} C${a.start.x + 130} ${a.start.y + 60} ${a.end.x - 60} ${a.end.y - 100} ${a.end.x} ${a.end.y}`) },
    { id: 'fulfillment-email', from: 'fulfillment', to: 'email', fromColor: 'var(--blue)', toColor: 'var(--red)', markers: {}, path: curve('fulfillment-email', ({ from, to, anchors: a }) => { const x = a.start.x - 4; return `M${x} ${a.start.y} C${x - 70} ${a.start.y + 55} ${a.end.x + 10} ${a.end.y - 55} ${a.end.x} ${a.end.y}`; }) },
    { id: 'fulfillment-whatsapp', from: 'fulfillment', to: 'whatsapp', fromColor: 'var(--blue)', toColor: 'var(--yellow)', markers: {}, path: curve('fulfillment-whatsapp', ({ from, to, anchors: a }) => `M${a.start.x} ${a.start.y} C${from.position.x + 55} ${from.position.y + 95} ${to.position.x - 25} ${to.position.y - 70} ${a.end.x} ${a.end.y}`) },
  ],
  ambient: { enabled: true, count: 1280, colors: ['var(--cyan)', 'var(--blue)', 'var(--cyan)', 'var(--green)', 'var(--orange)', 'var(--violet)', 'var(--red)', 'var(--yellow)'], opacity: 1, connectionOpacity: .07, reach: 38, seed: 'dexstoore', movement: true, speed: .00065, hubs: [{ x: 404, y: 206, bias: 1.05 }, { x: 388, y: 334, bias: 1.35 }, { x: 108, y: 498, bias: 1 }, { x: 648, y: 486, bias: 1.08 }] },
  animation: {
    enabled: true, duration: 440, stagger: 136, easing: 'cubic-bezier(.22,1,.36,1)', respectReducedMotion: true,
    build: {
      sequence: ['storefront', 'commerce-api', 'order-engine', 'operations', 'fulfillment', 'email', 'whatsapp'],
      geometry: { effect: 'fade-scale', duration: 440 },
      labels: { effect: 'fade', duration: 360, delay: 80 },
      connections: { effect: 'draw', duration: 560, delay: 110, sequence: ['storefront-commerce-api', 'commerce-api-order-engine', 'order-engine-operations', 'order-engine-fulfillment', 'fulfillment-email', 'fulfillment-whatsapp'] },
      ambient: { effect: 'fade', duration: 460, delay: 248 },
    },
  },
  interaction: { drag: { enabled: true, bounds: 'container' } },
};

type Config = NodeweaveOptions;
const scene = document.querySelector<HTMLElement>('#scene')!;
const panel = document.querySelector<HTMLElement>('#panel')!;
const status = document.querySelector<HTMLElement>('#status')!;
const clone = (source: Config): Config => ({ ...source, nodes: source.nodes.map((node) => ({ ...node, position: { ...node.position }, ...(node.labelPosition ? { labelPosition: { ...node.labelPosition } } : {}), ...(node.geometry ? { geometry: { ...node.geometry } } : {}) })), ...(source.connections ? { connections: source.connections.map((connection) => ({ ...connection, ...(connection.markers ? { markers: { ...connection.markers } } : {}) })) } : {}), ...(source.ambient ? { ambient: { ...source.ambient, ...(source.ambient.colors ? { colors: [...source.ambient.colors] } : {}), ...(source.ambient.hubs ? { hubs: source.ambient.hubs.map((hub) => ({ ...hub })) } : {}) } } : {}), ...(source.animation ? { animation: { ...source.animation, ...(source.animation.build ? { build: { ...source.animation.build, ...(source.animation.build.geometry ? { geometry: { ...source.animation.build.geometry } } : {}), ...(source.animation.build.labels ? { labels: { ...source.animation.build.labels } } : {}), ...(source.animation.build.connections ? { connections: { ...source.animation.build.connections } } : {}), ...(source.animation.build.ambient ? { ambient: { ...source.animation.build.ambient } } : {}) } } : {}) } } : {}), ...(source.interaction ? { interaction: { ...source.interaction, ...(source.interaction.drag ? { drag: { ...source.interaction.drag } } : {}) } } : {}), ...(source.typography ? { typography: { ...source.typography } } : {}) });
const baseline = clone(dexstoore); let current = clone(baseline); let selected = current.nodes[0]!.id; let network: Nodeweave;
const expandedSections = new Set(['ambient']);
const selectedNode = () => current.nodes.find((node) => node.id === selected)!;
const number = (id: string, value: number, min = 0, max = 2000, step = 1): string => `<div class="field"><label for="${id}">${id.replace(/-/g, ' ')}</label><input id="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;
const check = (id: string, checked: boolean): string => `<div class="field check"><label for="${id}">${id.replace(/-/g, ' ')}</label><input id="${id}" type="checkbox" ${checked ? 'checked' : ''}></div>`;
function renderPanel(): void {
  const node = selectedNode(); const ambient = current.ambient!; const animation = current.animation!; const build = animation.build!; const drag = current.interaction?.drag;
  const disclosure = (id: string, title: string, content: string): string => `<section class="section disclosure"><button class="section-toggle" type="button" data-section="${id}" aria-expanded="${expandedSections.has(id)}"><span>${title}</span><span aria-hidden="true">${expandedSections.has(id) ? '▾' : '›'}</span></button><div class="section-content" ${expandedSections.has(id) ? '' : 'hidden'}>${content}</div></section>`;
  const selectedContent = `<div class="field"><label for="selected-node">node</label><select id="selected-node">${current.nodes.map((item) => `<option value="${item.id}" ${item.id === selected ? 'selected' : ''}>${item.id}</option>`).join('')}</select></div><div class="field"><label for="node-label">label</label><input id="node-label" value="${escapeHtml(node.label)}"></div><div class="field"><label for="node-detail">detail</label><input id="node-detail" value="${escapeHtml(node.detail ?? '')}"></div>${number('node-x', network.getLayout()[node.id]?.x ?? node.position.x, -1000, 2000)}${number('node-y', network.getLayout()[node.id]?.y ?? node.position.y, -1000, 2000)}${number('node-size', node.geometry?.coreRadius ?? 4, .1, 40, .1)}<div class="field"><label for="node-color">color</label><input id="node-color" type="color" value="${toHex(node.color ?? '#58daf5')}"></div>${check('node-draggable', node.draggable !== false)}`;
  panel.innerHTML = `<h1 class="brand">NODEWEAVE<br><small>Live configurator</small></h1><section class="section selected-section"><h2>Selected node <span class="readonly">${node.id}</span></h2>${selectedContent}</section>${disclosure('general', 'General', number('seed', Number(String(ambient.seed).replace(/\D/g, '')) || 1, 0, 999999))}${disclosure('nodes', 'Nodes', `${number('node-opacity', node.opacity ?? 1, 0, 1, .05)}${number('label-size', Number(String(current.typography?.labelSize ?? 14).replace(/\D/g, '')), 6, 48)}${number('detail-size', Number(String(current.typography?.detailSize ?? 11).replace(/\D/g, '')), 6, 48)}`)}${disclosure('connections', 'Connections', `${number('connection-width', current.connections?.[0]?.width ?? 1, .1, 10, .1)}${number('connection-opacity', current.connections?.[0]?.opacity ?? .72, 0, 1, .05)}<div class="field"><label for="connection-color">color</label><input id="connection-color" type="color" value="#58daf5"></div>`)}${disclosure('ambient', 'Ambient', `${check('ambient-enabled', Boolean(ambient.enabled))}${number('ambient-count', ambient.count ?? 300, 0, 1500)}${number('ambient-opacity', ambient.opacity ?? 1, 0, 1, .05)}${number('ambient-reach', ambient.reach ?? 38, 1, 200)}${number('ambient-speed', ambient.speed ?? .00065, 0, .01, .00005)}${check('ambient-movement', Boolean(ambient.movement))}`)}${disclosure('animation', 'Animation', `${check('animation-enabled', animation.enabled !== false)}${number('geometry-duration', build.geometry?.duration ?? animation.duration ?? 440, 0, 2000)}${number('label-duration', build.labels?.duration ?? 360, 0, 2000)}${number('connection-duration', build.connections?.duration ?? 560, 0, 2000)}${number('stagger', animation.stagger ?? 100, 0, 1000)}<div class="field"><label for="node-effect">node effect</label><select id="node-effect"><option value="fade-scale">fade-scale</option><option value="fade">fade</option><option value="scale">scale</option></select></div><div class="field"><label for="connection-effect">connection</label><select id="connection-effect"><option value="draw">draw</option><option value="fade">fade</option></select></div>`)}${disclosure('interaction', 'Interaction', `${check('drag-enabled', Boolean(drag?.enabled))}<div class="field"><label for="bounds">bounds</label><select id="bounds"><option value="container">container</option><option value="none">none</option></select></div>`)}<section class="section actions-section"><div class="actions"><button id="replay" type="button">Replay</button><button id="reset" type="button">Reset</button><button id="copy" type="button">Copy config</button></div></section>`;
  bindControls();
}
const escapeHtml = (value: string): string => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));
const toHex = (color: string): string => { const tones: Record<string, string> = { 'var(--orange)': '#ffac67', 'var(--cyan)': '#58daf5', 'var(--violet)': '#b493ff', 'var(--green)': '#6be0a0', 'var(--blue)': '#73a9ff', 'var(--red)': '#ff6b78', 'var(--yellow)': '#f9df70' }; return /^#[0-9a-f]{6}$/i.test(color) ? color : tones[color] ?? '#58daf5'; };
const input = (id: string) => document.querySelector<HTMLInputElement | HTMLSelectElement>(`#${id}`)!;
const checkbox = (id: string) => document.querySelector<HTMLInputElement>(`#${id}`)!;
function mount(): void { network?.destroy(); network = new Nodeweave(scene, { ...current, interaction: { drag: { ...current.interaction?.drag, onStart: ({ id }) => { selected = id; renderPanel(); }, onMove: ({ id }) => { selected = id; const layout = network.getLayout()[id]!; const x = document.querySelector<HTMLInputElement>('#node-x'); const y = document.querySelector<HTMLInputElement>('#node-y'); if (x) x.value = String(Math.round(layout.x)); if (y) y.value = String(Math.round(layout.y)); } } } }); network.element.addEventListener('pointerdown', (event) => { const hit = (event.target as Element).closest<SVGRectElement>('[data-nodeweave-hit]'); if (hit?.dataset.nodeweaveHit) { selected = hit.dataset.nodeweaveHit; renderPanel(); } }); }
function updateSelected(update: Parameters<Nodeweave['updateNode']>[1]): void { const node = selectedNode(); Object.assign(node, update); if (update.geometry) node.geometry = { ...node.geometry, ...update.geometry }; network.updateNode(node.id, update); }
function bindControls(): void {
  for (const button of document.querySelectorAll<HTMLButtonElement>('.section-toggle')) button.addEventListener('click', () => { const id = button.dataset.section!; if (expandedSections.has(id)) expandedSections.delete(id); else expandedSections.add(id); const content = button.nextElementSibling; const expanded = expandedSections.has(id); button.setAttribute('aria-expanded', String(expanded)); button.querySelector('[aria-hidden="true"]')!.textContent = expanded ? '▾' : '›'; content?.toggleAttribute('hidden', !expanded); });
  const on = (id: string, listener: () => void) => input(id).addEventListener('input', listener);
  on('seed', () => { current.ambient!.seed = Number(input('seed').value); network.updateAmbient({ seed: current.ambient!.seed }); });
  on('node-opacity', () => updateSelected({ opacity: Number(input('node-opacity').value) })); on('label-size', () => { current.typography = { ...current.typography, labelSize: Number(input('label-size').value) }; network.updateTypography(current.typography); }); on('detail-size', () => { current.typography = { ...current.typography, detailSize: Number(input('detail-size').value) }; network.updateTypography(current.typography); });
  on('connection-width', () => { const width = Number(input('connection-width').value); for (const connection of current.connections ?? []) { connection.width = width; network.updateConnection(connection.id!, { width }); } }); on('connection-opacity', () => { const opacity = Number(input('connection-opacity').value); for (const connection of current.connections ?? []) { connection.opacity = opacity; network.updateConnection(connection.id!, { opacity }); } }); input('connection-color').addEventListener('input', () => { const color = input('connection-color').value; for (const connection of current.connections ?? []) { connection.color = color; network.updateConnection(connection.id!, { color }); } });
  const ambientUpdate = (): void => { const update = { enabled: checkbox('ambient-enabled').checked, count: Number(input('ambient-count').value), opacity: Number(input('ambient-opacity').value), reach: Number(input('ambient-reach').value), speed: Number(input('ambient-speed').value), movement: checkbox('ambient-movement').checked }; Object.assign(current.ambient!, update); network.updateAmbient(update); }; ['ambient-enabled','ambient-count','ambient-opacity','ambient-reach','ambient-speed','ambient-movement'].forEach((id) => on(id, ambientUpdate));
  const animationUpdate = (): void => { const buildUpdate = { geometry: { ...current.animation!.build?.geometry, duration: Number(input('geometry-duration').value), effect: input('node-effect').value as 'fade' | 'scale' | 'fade-scale' }, labels: { ...current.animation!.build?.labels, duration: Number(input('label-duration').value) }, connections: { ...current.animation!.build?.connections, duration: Number(input('connection-duration').value), effect: input('connection-effect').value as 'fade' | 'draw' } }; current.animation = { ...current.animation!, enabled: checkbox('animation-enabled').checked, stagger: Number(input('stagger').value), build: { ...current.animation!.build, ...buildUpdate } }; network.updateAnimation(current.animation); }; ['animation-enabled','geometry-duration','label-duration','connection-duration','stagger','node-effect','connection-effect'].forEach((id) => on(id, animationUpdate));
  const interactionUpdate = (): void => { current.interaction = { drag: { enabled: checkbox('drag-enabled').checked, bounds: input('bounds').value as 'container' | 'none' } }; network.updateInteraction(current.interaction); }; on('drag-enabled', interactionUpdate); input('bounds').addEventListener('change', interactionUpdate);
  input('selected-node').addEventListener('change', () => { selected = input('selected-node').value; renderPanel(); }); on('node-label', () => updateSelected({ label: input('node-label').value })); on('node-detail', () => updateSelected({ detail: input('node-detail').value })); const position = (): void => { const point = { x: Number(input('node-x').value), y: Number(input('node-y').value) }; network.setLayout({ [selected]: point }); current.nodes.find((node) => node.id === selected)!.position = { ...point }; }; on('node-x', position); on('node-y', position); on('node-size', () => updateSelected({ geometry: { coreRadius: Number(input('node-size').value) } })); input('node-color').addEventListener('input', () => updateSelected({ color: input('node-color').value })); on('node-draggable', () => updateSelected({ draggable: checkbox('node-draggable').checked }));
  document.querySelector<HTMLButtonElement>('#replay')!.addEventListener('click', () => network.replay()); document.querySelector<HTMLButtonElement>('#reset')!.addEventListener('click', () => { current = clone(baseline); selected = current.nodes[0]!.id; mount(); renderPanel(); }); document.querySelector<HTMLButtonElement>('#copy')!.addEventListener('click', copyConfig);
}
function serialize(): string { const layout = network.getLayout(); const paths: Record<string, string> = { 'order-engine-operations': '({ anchors: a }) => `M${a.start.x} ${a.start.y} C${a.start.x - 140} ${a.start.y + 70} ${a.end.x + 50} ${a.end.y - 110} ${a.end.x} ${a.end.y}`', 'order-engine-fulfillment': '({ anchors: a }) => `M${a.start.x} ${a.start.y} C${a.start.x + 130} ${a.start.y + 60} ${a.end.x - 60} ${a.end.y - 100} ${a.end.x} ${a.end.y}`', 'fulfillment-email': '({ anchors: a }) => { const x = a.start.x - 4; return `M${x} ${a.start.y} C${x - 70} ${a.start.y + 55} ${a.end.x + 10} ${a.end.y - 55} ${a.end.x} ${a.end.y}`; }', 'fulfillment-whatsapp': '({ from, to, anchors: a }) => `M${a.start.x} ${a.start.y} C${from.position.x + 55} ${from.position.y + 95} ${to.position.x - 25} ${to.position.y - 70} ${a.end.x} ${a.end.y}`' }; const options = { ...current, nodes: current.nodes.map((node) => ({ ...node, position: layout[node.id] })), connections: current.connections?.map((connection) => ({ ...connection, ...(paths[connection.id ?? ''] ? { path: `__NODEWEAVE_PATH_${connection.id}` } : {}) })) }; let code = JSON.stringify(options, null, 2).replace(/"([^"\n]+)":/g, '$1:'); for (const [id, path] of Object.entries(paths)) code = code.replace(`"__NODEWEAVE_PATH_${id}"`, path); return `import { Nodeweave, type NodeweaveOptions } from 'nodeweave';\n\nconst options: NodeweaveOptions = ${code};\n\nconst weave = new Nodeweave(document.querySelector<HTMLElement>('#network')!, options);\n`; }
async function copyConfig(): Promise<void> { try { await navigator.clipboard.writeText(serialize()); status.textContent = '✓ CONFIG COPIED'; window.setTimeout(() => { status.textContent = ''; }, 1600); } catch { status.textContent = 'COPY FAILED'; } }
mount(); renderPanel();
